### ISSUE TITLE
prefetch_gather

### ISSUE THREAD

**Issue by fzhedu** [PatrickXC/hash_join_codes_KNL#1]
Hi,
Do you test the intrinsics about prefetch_gather to improve the join operator?

**Comment by xtcyclist** [comment]
I have tried doing that. But I didn't get any impressive speedup. So I leave it there for now.

**Comment by fzhedu** [comment]
Thanks for your reply.
Even without prefetch, is the performance of gather faster than accessing data by scalar code? regardless of continuous or non-continuous data access. 
I see the answer is NO from the stackoverflow website.
https://stackoverflow.com/questions/24756534/in-what-situation-would-the-avx2-gather-instructions-be-faster-than-individually
https://stackoverflow.com/questions/21774454/how-are-the-gather-instructions-in-avx2-implemented/21778409#21778409

**Comment by xtcyclist** [comment]
If you have a specific code, you should test it. 
For this hash join case of mine, it is a non-issue. Because we cannot afford to move the data out of the SIMD registers. Maybe gather is slower than scalar, maybe it's not, but keeping the data in SIMD registers delivers the best performance overall.

**Comment by fzhedu** [comment]
From my experiments, the gathers of AVX2 and AVX512 are both slower than scalar code in case of random access.
Thanks.
